"""Rebuild the Coinford logo as SVG from the vector artwork inside the official
Blackwall Reach case study PDF (the website only serves a white PNG).

Run: python3 scripts/logo.py   (needs `pip install pymupdf`)
Writes public/brand/*.svg and lib/logo.ts (the separate shapes the preloader animates).
"""
import json, os, urllib.request
import fitz  # PyMuPDF

PDF_URL = "https://www.coinford.co.uk/wp-content/uploads/2017/12/Coinford-Blackwall-Reach-CS-2018_web.pdf"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "_scrape", "brand", "blackwall.pdf")

if not os.path.exists(CACHE):
    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    req = urllib.request.Request(PDF_URL, headers={"User-Agent": "Mozilla/5.0"})
    open(CACHE, "wb").write(urllib.request.urlopen(req).read())

page = fitz.open(CACHE)[0]
drawings = page.get_drawings()
# The logo occupies the top-left of the page: two navy tiles (mark + wordmark) with white shapes knocked out on top.
OX, OY = 28.346, 28.347  # top-left of the mark tile, becomes 0,0

def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")

def to_path(d):
    out, cur = [], None
    for it in d["items"]:
        kind = it[0]
        if kind == "l":
            a, b = it[1], it[2]
            if cur is None or abs(cur.x - a.x) > 1e-3 or abs(cur.y - a.y) > 1e-3:
                out.append(f"M{f(a.x-OX)} {f(a.y-OY)}")
            out.append(f"L{f(b.x-OX)} {f(b.y-OY)}"); cur = b
        elif kind == "c":
            a, c1, c2, b = it[1], it[2], it[3], it[4]
            if cur is None or abs(cur.x - a.x) > 1e-3 or abs(cur.y - a.y) > 1e-3:
                out.append(f"M{f(a.x-OX)} {f(a.y-OY)}")
            out.append(f"C{f(c1.x-OX)} {f(c1.y-OY)} {f(c2.x-OX)} {f(c2.y-OY)} {f(b.x-OX)} {f(b.y-OY)}"); cur = b
        elif kind == "re":
            r = it[1]
            out.append(f"M{f(r.x0-OX)} {f(r.y0-OY)}H{f(r.x1-OX)}V{f(r.y1-OY)}H{f(r.x0-OX)}Z"); cur = None
        elif kind == "qu":
            q = it[1]
            out.append(f"M{f(q.ul.x-OX)} {f(q.ul.y-OY)}L{f(q.ur.x-OX)} {f(q.ur.y-OY)}L{f(q.lr.x-OX)} {f(q.lr.y-OY)}L{f(q.ll.x-OX)} {f(q.ll.y-OY)}Z"); cur = None
    if d.get("closePath"):
        out.append("Z")
    # Close every subpath that returns to its start so fills are clean.
    return "".join(out).replace("M", "ZM").lstrip("Z").replace("ZZ", "Z") + ("" if "".join(out).endswith("Z") else "Z")

fills = [d for d in drawings if d.get("fill") is not None and d["rect"].y1 < 70 and d["rect"].x0 > 20]
by_index = {i: d for i, d in enumerate(drawings)}
names = {2: "markTile", 3: "wordTile", 4: "shield", 5: "lion", 6: "eye", 7: "C", 8: "o", 9: "i", 10: "n", 11: "f", 12: "o2", 13: "r", 14: "d"}
parts = {}
for i, name in names.items():
    d = by_index[i]
    parts[name] = {"d": to_path(d), "evenodd": bool(d.get("even_odd")), "box": [round(d["rect"].x0 - OX, 3), round(d["rect"].y0 - OY, 3), round(d["rect"].width, 3), round(d["rect"].height, 3)]}

navy_rgb = by_index[2]["fill"]
NAVY_PDF = "#%02x%02x%02x" % tuple(round(c * 255) for c in navy_rgb)
W = round(by_index[3]["rect"].x1 - OX, 3)
H = round(by_index[3]["rect"].y1 - OY, 3)
MW = round(by_index[2]["rect"].x1 - OX, 3)

def p(name, fill):
    rule = ' fill-rule="evenodd"' if parts[name]["evenodd"] else ""
    return f'<path d="{parts[name]["d"]}" fill="{fill}"{rule}/>'

letters = ["C", "o", "i", "n", "f", "o2", "r", "d"]
NAVY = "#1E2C51"  # digital navy from the official favicon (cropped-coinford-192x192.jpg)

def svg(w, h, body, vb=None):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb or f"0 0 {w} {h}"}" width="{w}" height="{h}">{body}</svg>\n'

brand = os.path.join(ROOT, "public", "brand")
os.makedirs(brand, exist_ok=True)
# Full lock-up as printed: navy tiles with white knock-out shapes.
full = p("markTile", NAVY) + p("wordTile", NAVY) + p("shield", "#fff") + p("lion", "#fff") + p("eye", NAVY) + "".join(p(l, "#fff") for l in letters)
open(os.path.join(brand, "logo-tile.svg"), "w").write(svg(W, H, full))
# White-only lock-up for navy or photographic backgrounds (transparent).
white = p("shield", "#fff") + p("lion", "#fff") + "".join(p(l, "#fff") for l in letters)
open(os.path.join(brand, "logo-white.svg"), "w").write(svg(W, H, white))
# Navy-only lock-up for white backgrounds (transparent). The shield ring and lion read as navy line art.
navy = p("shield", NAVY) + p("lion", NAVY) + p("eye", "#fff") + "".join(p(l, NAVY) for l in letters)
open(os.path.join(brand, "logo-navy.svg"), "w").write(svg(W, H, navy))
# The mark on its own (favicon / app icon).
mark = p("markTile", NAVY) + p("shield", "#fff") + p("lion", "#fff") + p("eye", NAVY)
open(os.path.join(brand, "mark.svg"), "w").write(svg(MW, H, mark, f"0 0 {MW} {H}"))
open(os.path.join(ROOT, "app", "icon.svg"), "w").write(svg(MW, H, mark, f"0 0 {MW} {H}"))

ts = "// Generated by scripts/logo.py from the vector logo in the official Blackwall Reach case study PDF. Do not edit by hand.\n"
ts += f"export const logoSize = {{ width: {W}, height: {H}, markWidth: {MW} }};\n"
ts += f"// Navy sampled from the PDF artwork: {NAVY_PDF}. The site uses the favicon navy {NAVY} instead.\n"
ts += "export const logoParts = " + json.dumps({k: {"d": v["d"], "evenodd": v["evenodd"]} for k, v in parts.items()}, indent=2) + " as const;\n"
ts += "export const letterOrder = " + json.dumps(letters) + " as const;\n"
open(os.path.join(ROOT, "lib", "logo.ts"), "w").write(ts)
print("logo", W, "x", H, "mark", MW, {k: (v["evenodd"], len(v["d"])) for k, v in parts.items()})
